apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}--organizer--d
  labels:
    app: {{ include "platform.fullname" . }}--organizer
    name: {{ include "platform.fullname" . }}--organizer--d
    chart: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "platform.fullname" . }}--organizer
      name: {{ include "platform.fullname" . }}--organizer
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ include "platform.fullname" . }}--organizer
        name: {{ include "platform.fullname" . }}--organizer
        chart: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "platform.fullname" . }}--platform--sa
      volumes:
        - name: organizer-config
          secret:
            secretName: {{ template "platform.fullname" . }}--organizer-secret--sec
      containers:
        - name: {{ template  "platform.fullname" . }}--organizer
          image: "{{ .Values.organizer.image.repository }}:{{ .Values.organizer.image.tag }}"
          imagePullPolicy: {{ .Values.organizer.image.pullPolicy }}
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: organizer-config
              mountPath: /repo/modules/@frontend_organizer-app/.env
              subPath: production.env
          env:
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            initialDelaySeconds: 60
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 20
            initialDelaySeconds: 60
            periodSeconds: 30

