apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}--organizer--d
  labels:
    app: {{ include "platform.fullname" . }}--organizer
    name: {{ include "platform.fullname" . }}--organizer--d
    chart: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "platform.fullname" . }}--organizer
      name: {{ include "platform.fullname" . }}--organizer
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ include "platform.fullname" . }}--organizer
        name: {{ include "platform.fullname" . }}--organizer
        chart: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "platform.fullname" . }}--platform--sa
      volumes:
        - name: organizer-config-well-known
          configMap:
            name: {{ template "platform.fullname" . }}--organizer-config-well-known--cfmp
      containers:
        - name: {{ template  "platform.fullname" . }}--organizer
          image: "{{ .Values.organizer.image.repository }}:{{ .Values.organizer.image.tag }}"
          imagePullPolicy: {{ .Values.organizer.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: REACT_APP_BUG_REPORT_LINK
              value: '{{ required "[organizer] Missing config.bugReportLink value" .Values.config.bugReportLink }}'
            - name: REACT_APP_T721_SERVER_HOST
              value: '{{ required "[organizer] Missing config.serverEndpoint.host value" .Values.config.serverEndpoint.host }}'
            - name: REACT_APP_T721_SERVER_PORT
              value: '{{ required "[organizer] Missing config.serverEndpoint.port value" .Values.config.serverEndpoint.port }}'
            - name: REACT_APP_T721_SERVER_PROTOCOL
              value: '{{ required "[organizer] Missing config.serverEndpoint.protocol value" .Values.config.serverEndpoint.protocol }}'
            - name: REACT_APP_STRIPE_API_KEY
              value: '{{ required "[organizer] Missing config.organizer.publishableStripeApiKey value" .Values.config.organizer.publishableStripeApiKey }}'
            - name: REACT_APP_GOOGLE_PLACES_API_KEY
              value: '{{ required "[organizer] Missing config.googleGeocodingApiKey value" .Values.config.googleGeocodingApiKey }}'
            - name: REACT_APP_SEGMENT_API_KEY
              value: '{{ required "[organizer] Missing config.organizer.segmentApiKey value" .Values.config.organizer.segmentApiKey }}'
            - name: REACT_APP_ERROR_THRESHOLD
              value: '5'
            - name: REACT_APP_SENTRY_DSN
              value: {{ required "[t721app] Missing config.organizer.sentry_dsn" .Values.config.organizer.sentry_dsn}}
            - name: REACT_APP_SELF
              value: 'https://{{ required "[organizer] Missing config.organizer.self value" .Values.config.organizer.self }}'
            - name: REACT_APP_USER_URL
              value: 'https://{{ required "[organizer] Missing config.organizer.appUrl value" .Values.config.organizer.appUrl }}'
            - name: REACT_APP_GA_ID
              value: '{{ required "[organizer] Missing config.organizer.gaId value" .Values.config.organizer.gaId }}'
            - name: REACT_APP_GOOGLE_AUTH_CLIENT_ID
              value: '{{ required "[organizer] Missing config.googleAuthClientId value" .Values.config.googleAuthClientId }}'
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: organizer-config-well-known
              mountPath: /repo/modules/@frontend_organizer-app/build/.well-known/apple-developer-merchantid-domain-association
              subPath: apple-developer-merchantid-domain-association
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

