apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "ingress.fullname" . }}--ingress
  labels:
    name: {{ include "ingress.fullname" . }}--ingress
    chart: {{ .Chart.Name }}
spec:
  rules:
    {{- range .Values.hosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .route }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
          {{- end }}
    {{- end }}
