# Config files mounted in /usr/share/cassandra/conf
# (it cannot be mounted in /etc/cassandra because chowned to cassandra in the docker-entrypoint.sh)
{{- if .Values.storage.elassandra.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "env.fullname" . }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "env.name" . }}
    chart: {{ template "env.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.storage.elassandra.extraLabels }}
{{ toYaml .Values.storage.elassandra.extraLabels | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.storage.elassandra.configs }}
  {{ $key }}: |-
{{  $val | indent 4 }}
{{- end }}
{{- end }}
