apiVersion: v1
kind: Service
metadata:
  name: {{ template "env.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # https://github.com/kubernetes/examples/issues/89
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "env.name" . }}
    chart: {{ template "env.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: jmx
    port: 7199
    targetPort: 7199
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: transport
    port: {{ default 9300 .Values.storage.elassandra.config.ports.transport }}
    targetPort: {{ default 9300 .Values.storage.elassandra.config.ports.transport }}
  - name: cql
    port: {{ default 9042 .Values.storage.elassandra.config.ports.cql }}
    targetPort: {{ default 9042 .Values.storage.elassandra.config.ports.cql }}
  - name: thrift
    port: {{ default 9160 .Values.storage.elassandra.config.ports.thrift }}
    targetPort: {{ default 9160 .Values.storage.elassandra.config.ports.thrift }}
  - name: elasticsearch
    port: {{ default 9200 .Values.storage.elassandra.config.ports.elasticsearch }}
    targetPort: {{ default 9200 .Values.storage.elassandra.config.ports.elasticsearch }}
{{- if .Values.storage.elassandra.config.ports.agent }}
  - name: agent
    port: {{ .Values.storage.elassandra.config.ports.agent }}
    targetPort: {{ .Values.storage.elassandra.config.ports.agent }}
{{- end }}
{{- if .Values.storage.elassandra.debug.enabled }}
  - name: jdwp
    port: {{ default 4242 .Values.storage.elassandra.debug.port }}
    targetPort: {{ default 4242 .Values.storage.elassandra.debug.port }}
{{- end }}
  selector:
    app: {{ template "env.name" . }}
    release: {{ .Release.Name }}
