redis:
  usePassword: false

  master:
    priorityClassName: redis--priority
    resources:
      requests:
        memory: 256Mi
        cpu: 250m

    persistence:
      size: 50Gi

  slave:
    priorityClassName: redis--priority
    resources:
      requests:
        memory: 256Mi
        cpu: 250m

    persistence:
      size: 50Gi
