apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingress.fullname" . }}--nginx-ingress--d
  labels:
    name: {{ include "ingress.fullname" . }}--nginx-ingress--d
    chart: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ingress.fullname" . }}--nginx-ingress--app
  template:
    metadata:
      labels:
        app: {{ include "ingress.fullname" . }}--nginx-ingress--app
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
    spec:
      serviceAccountName: {{ include "ingress.fullname" . }}--nginx-ingress--sa
      containers:
      - image: nginx/nginx-ingress:1.7.0
        name: {{ include "ingress.fullname" . }}--nginx-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
       #- name: prometheus
         #containerPort: 9113
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/{{ include "ingress.fullname" . }}--nginx-config--cfmp
          - -default-server-tls-secret=$(POD_NAMESPACE)/{{ include "ingress.fullname" . }}--nginx-default-server-secret--sct
         #- -v=3 # Enables extensive logging. Useful for troubleshooting.
         #- -report-ingress-status
         #- -external-service=nginx-ingress
         #- -enable-leader-election
         #- -enable-prometheus-metrics
         #- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
