# Default values for platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

migrations:
  image:
    repository: migrations
    pullPolicy: IfNotPresent
    tag: "DEVELOPMENT"

staff:

  image:
    repository: staff
    pullPolicy: IfNotPresent
    tag: "DEVELOPMENT"

  service:
    type: LoadBalancer
    port: 80

t721app:

  image:
    repository: t721app
    pullPolicy: IfNotPresent
    tag: "DEVELOPMENT"

  service:
    type: LoadBalancer
    port: 80

organizer:

  image:
    repository: organizer
    pullPolicy: IfNotPresent
    tag: "DEVELOPMENT"

  service:
    type: LoadBalancer
    port: 80

server:

  slave:
    replicas: 1

  master:
    replicas: 1

  fsName: ""

  image:
    repository: server
    pullPolicy: IfNotPresent
    tag: "DEVELOPMENT"

  service:
    type: LoadBalancer
    port: 80

