# Scripts files mounted in /usr/share/cassandra/scripts
{{- if .Values.inits }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elassandra.fullname" . }}-inits
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "elassandra.name" . }}
    chart: {{ template "elassandra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{- range $key, $val := .Values.inits }}
  {{ $key }}: |-
{{  $val | indent 4 }}
{{- end }}
{{- end }}
