name: Comment Dependabot Merge Command
on: pull_request

jobs:
    ordermerge:
        runs-on: ubuntu-latest

        steps:
            - name: Comment "@dependabot squash and merge"
              uses: unsplash/comment-on-pr@master
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
              env:
                  GITHUB_TOKEN: ${{ secrets.COMMENT_TOKEN }}
              with:
                  msg: "@dependabot squash and merge"
