name: T721 Monorepo Staging CD

on:
  schedule:
    - cron:  '0 8 * * *'
  push:
    tags:
      - staging-*

jobs:
    docker:
      name: "[S3] docker"
      runs-on: ubuntu-latest
      steps:

        - name: Wait for build to succeed
          uses: fountainhead/action-wait-for-check@v1.0.0
          id: wait-for-build
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            checkName: end
            ref: ${{ github.sha }}

        - uses: actions/checkout@v2.3.4
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')

        - name: "Use Node.js 12.x"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          uses: actions/setup-node@v2.1.2
          with:
            node-version: 12.x

        - name: "Setup SSH Agent"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          uses: webfactory/ssh-agent@master
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: "Install required tools globally (npm install -g lerna lcov-result-merger yarn)"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          run: npm install -g lerna@3.16.4 lcov-result-merger@3.1.0 yarn@1.22.4

        - name: "Recover submodules (yarn setup:submodules:clone)"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          run: yarn setup:submodules:clone

        - name: "Setup aws CLI"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          uses: chrislennon/action-aws-cli@v1.1

        - name: Check if images already exist
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success')
          id: should_build
          run: yarn @docker:build:check
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

        - name: "Authenticate Docker"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success') && steps.should_build.outputs.should_build == 'true'
          run: ./aws-ecr-login.sh
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

        - name: "Build all docker images"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success') && steps.should_build.outputs.should_build == 'true'
          run: yarn @docker:build:github

        - name: "Publish to Elastic Container Registry"
          if: (github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success') && steps.should_build.outputs.should_build == 'true'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
          run: yarn @docker:deploy:github

    infra:
      name: "[S4] infra (staging)"
      needs: docker
      runs-on: ubuntu-latest
      steps:

        - name: Wait for build to succeed
          uses: fountainhead/action-wait-for-check@v1.0.0
          id: wait-for-build
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            checkName: end
            ref: ${{ github.sha }}

        - uses: actions/checkout@v2.3.4
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
        - name: "Use Node.js 12.x"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          uses: actions/setup-node@v2.1.2
          with:
            node-version: 12.x

        - name: "Setup SSH Agent"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          uses: webfactory/ssh-agent@master
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: "Install required tools globally (npm install -g lerna lcov-result-merger yarn)"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: npm install -g lerna@3.16.4 lcov-result-merger@3.1.0 yarn@1.22.4

        - name: "Recover submodules (yarn setup:submodules:clone)"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: yarn setup:submodules:clone

        - name: "Setup aws CLI"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install && aws --version

        - name: "Setup kubectl"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.2/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

        - name: "Setup kubeconfig"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: aws eks update-kubeconfig --name ${CONFIG_STAGING_CLUSTER_NAME} && kubectl get pod && chmod 600 ~/.kube/config
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
            CONFIG_STAGING_CLUSTER_NAME: ${{ secrets.CONFIG_STAGING_CLUSTER_NAME }}

        - name: "Setup Helm + Helm Diff"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/v3.3.1/scripts/get-helm-3 | bash && helm plugin install https://github.com/databus23/helm-diff --version v3.1.1 && helm version

        - name: "Setup Helmsman"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: curl -L https://github.com/Praqma/helmsman/releases/download/v3.4.1/helmsman_3.4.1_linux_amd64.tar.gz | tar zx && chmod +x helmsman && sudo mv ./helmsman /usr/local/bin/helmsman && helmsman --verbose

        - name: "Fetch Helm Repos and Dependencies"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: ./helm_prepare.sh

        - name: "Helmsman on staging infra"
          if: github.event_name == 'push' || steps.wait-for-build.outputs.conclusion == 'success'
          run: ./helmsman.apply.staging.sh
          env:
            CONFIG_STAGING_STRIPE_APIKEY: ${{ secrets.CONFIG_STAGING_STRIPE_APIKEY }}
            CONFIG_STAGING_MAILJET_APIKEY: ${{ secrets.CONFIG_STAGING_MAILJET_APIKEY }}
            CONFIG_STAGING_MAILJET_APISECRET: ${{ secrets.CONFIG_STAGING_MAILJET_APISECRET }}
            CONFIG_STAGING_JWT_SECRET: ${{ secrets.CONFIG_STAGING_JWT_SECRET }}
            CONFIG_STAGING_ROUTE53_KEY: ${{ secrets.CONFIG_STAGING_ROUTE53_KEY }}
            CONFIG_STAGING_ROUTE53_SECRET: ${{ secrets.CONFIG_STAGING_ROUTE53_SECRET }}
            CONFIG_STAGING_ROUTE53_HOSTEDZONE: ${{ secrets.CONFIG_STAGING_ROUTE53_HOSTEDZONE }}
            CONFIG_STAGING_ACME_SERVER: ${{ secrets.CONFIG_STAGING_ACME_SERVER }}
            CONFIG_STAGING_GCLOUD_GEOLOC_APIKEY: ${{ secrets.CONFIG_STAGING_GCLOUD_GEOLOC_APIKEY }}
            CONFIG_STAGING_ORGANIZER_SEGMENT_API_KEY: ${{ secrets.CONFIG_STAGING_ORGANIZER_SEGMENT_API_KEY }}
            CONFIG_STAGING_T721APP_SEGMENT_API_KEY: ${{ secrets.CONFIG_STAGING_T721APP_SEGMENT_API_KEY }}
            CONFIG_STAGING_STAFF_SEGMENT_API_KEY: ${{ secrets.CONFIG_STAGING_STAFF_SEGMENT_API_KEY }}
            CONFIG_STAGING_T721APP_PUBLISHABLE_STRIPE_API_KEY: ${{ secrets.CONFIG_STAGING_T721APP_PUBLISHABLE_STRIPE_API_KEY }}
            CONFIG_STAGING_ORGANIZER_PUBLISHABLE_STRIPE_API_KEY: ${{ secrets.CONFIG_STAGING_ORGANIZER_PUBLISHABLE_STRIPE_API_KEY }}
            CONFIG_STAGING_T721APP_ITUNES_ID: ${{ secrets.CONFIG_STAGING_T721APP_ITUNES_ID }}
            CONFIG_STAGING_T721APP_APPSTORE_LINK: ${{ secrets.CONFIG_STAGING_T721APP_APPSTORE_LINK }}
            CONFIG_STAGING_T721APP_PLAYSTORE_LINK: ${{ secrets.CONFIG_STAGING_T721APP_PLAYSTORE_LINK }}
            CONFIG_STAGING_IMAGE_S3_REGION: ${{ secrets.CONFIG_STAGING_IMAGE_S3_REGION }}
            CONFIG_STAGING_IMAGE_S3_ACCESS_KEY_ID: ${{ secrets.CONFIG_STAGING_IMAGE_S3_ACCESS_KEY_ID }}
            CONFIG_STAGING_IMAGE_S3_SECRET_ACCESS_KEY: ${{ secrets.CONFIG_STAGING_IMAGE_S3_SECRET_ACCESS_KEY }}
            CONFIG_STAGING_IMAGE_S3_BUCKET_NAME: ${{ secrets.CONFIG_STAGING_IMAGE_S3_BUCKET_NAME }}
            CONFIG_BUG_REPORT_LINK: ${{ secrets.CONFIG_BUG_REPORT_LINK }}
            CONFIG_STAGING_T721APP_APPLE_MERCHANT_ID: ${{ secrets.CONFIG_STAGING_T721APP_APPLE_MERCHANT_ID }}

            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_USER_ID: ${{ secrets.AWS_USER_ID }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

