apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "platform.fullname" . }}--server-config-feature-flags--cfmp
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ include "platform.fullname" . }}--server-config-feature-flags--cfmp
    chart: {{ .Chart.Name }}
data:
  feature-flags.json: |-
    {
      "admin_flag": {
        "active": false
      }
    }
