apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}--server--svc
  labels:
    name: {{ include "platform.fullname" . }}--server--svc
    chart: {{ .Chart.Name }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "platform.fullname" . }}--server
    chart: {{ .Chart.Name }}
