apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}--t721app--d
  labels:
    app: {{ include "platform.fullname" . }}--t721app
    name: {{ include "platform.fullname" . }}--t721app--d
    chart: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "platform.fullname" . }}--t721app
      name: {{ include "platform.fullname" . }}--t721app
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ include "platform.fullname" . }}--t721app
        name: {{ include "platform.fullname" . }}--t721app
        chart: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "platform.fullname" . }}--platform--sa
      volumes:
        - name: t721app-config-server-config
          configMap:
            name: {{ template "platform.fullname" . }}--t721app-config-server-config--cfmp
        - name: t721app-config-well-known
          configMap:
            name: {{ template "platform.fullname" . }}--t721app-config-well-known--cfmp
      containers:
        - name: {{ template  "platform.fullname" . }}--t721app
          image: "{{ .Values.t721app.image.repository }}:{{ .Values.t721app.image.tag }}"
          imagePullPolicy: {{ .Values.t721app.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            - name: REACT_APP_BUG_REPORT_LINK
              value: '{{ required "[organizer] Missing config.bugReportLink value" .Values.config.bugReportLink }}'
            - name: REACT_APP_T721_SERVER_HOST
              value: '{{ required "[t721app] Missing config.serverEndpoint.host value" .Values.config.serverEndpoint.host }}'
            - name: REACT_APP_T721_SERVER_PORT
              value: '{{ required "[t721app] Missing config.serverEndpoint.port value" .Values.config.serverEndpoint.port }}'
            - name: REACT_APP_T721_SERVER_PROTOCOL
              value: '{{ required "[t721app] Missing config.serverEndpoint.protocol value" .Values.config.serverEndpoint.protocol }}'
            - name: REACT_APP_STRIPE_API_KEY
              value: '{{ required "[t721app] Missing config.t721app.publishableStripeApiKey value" .Values.config.t721app.publishableStripeApiKey }}'
            - name: REACT_APP_SEGMENT_API_KEY
              value: '{{ required "[t721app] Missing config.t721app.segmentApiKey value" .Values.config.t721app.segmentApiKey }}'
            - name: REACT_APP_ITUNES_ID
              value: '{{ required "[t721app] Missing config.t721app.itunesId value" .Values.config.t721app.itunesId }}'
            - name: REACT_APP_APPSTORE_LINK
              value: '{{ required "[t721app] Missing config.t721app.appStoreLink value" .Values.config.t721app.appStoreLink }}'
            - name: REACT_APP_PLAYSTORE_LINK
              value: '{{ required "[t721app] Missing config.t721app.playStoreLink value" .Values.config.t721app.playStoreLink }}'
            - name: REACT_APP_ERROR_THRESHOLD
              value: '5'
            - name: REACT_APP_APPLE_PAY_MERCHANT_ID
              value: '{{ required "[t721app] Missing config.t721app.webMerchantId value" .Values.config.t721app.iosMerchantId }}'
            - name: REACT_APP_SENTRY_DSN
              value: {{ required "[t721app] Missing config.t721app.sentry_dsn" .Values.config.t721app.sentry_dsn}}
            - name: REACT_APP_EVENT_CREATION_LINK
              value: {{ required "[t721app] Missing config.t721app.createEventLink" .Values.config.t721app.createEventLink}}
            - name: REACT_APP_SELF
              value: 'https://{{ required "[t721app] Missing config.t721app.self value" .Values.config.t721app.self }}'
            - name: REACT_APP_GA_ID
              value: '{{ required "[t721app] Missing config.t721app.gaId value" .Values.config.t721app.gaId }}'
            - name: SITEMAP_ENABLED
              value: '{{ required "[t721app] Missing config.t721app.sitemapEnabled value" .Values.config.t721app.sitemapEnabled }}'
            - name: REACT_APP_GOOGLE_AUTH_CLIENT_ID
              value: '{{ required "[t721app] Missing config.googleAuthClientId value" .Values.config.googleAuthClientId }}'
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: t721app-config-server-config
              mountPath: /repo/modules/@frontend_t721-app/server.config.js
              subPath: server.config.js
            - name: t721app-config-well-known
              mountPath: /repo/modules/@frontend_t721-app/build/.well-known/apple-app-site-association
              subPath: apple-app-site-association
            - name: t721app-config-well-known
              mountPath: /repo/modules/@frontend_t721-app/build/.well-known/assetlinks.json
              subPath: assetlinks.json
            - name: t721app-config-well-known
              mountPath: /repo/modules/@frontend_t721-app/build/.well-known/apple-developer-merchantid-domain-association
              subPath: apple-developer-merchantid-domain-association
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

